// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: parsed_vision/parsed_vision.proto

package parsed_vision

import (
	ssl_vision "github.com/LiU-SeeGoals/proto_go/ssl_vision"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Robot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId     uint32              `protobuf:"varint,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Pos         *ssl_vision.Vector2 `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Orientation float32             `protobuf:"fixed32,3,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Vel         *ssl_vision.Vector2 `protobuf:"bytes,4,opt,name=vel,proto3" json:"vel,omitempty"`
}

func (x *Robot) Reset() {
	*x = Robot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parsed_vision_parsed_vision_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Robot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Robot) ProtoMessage() {}

func (x *Robot) ProtoReflect() protoreflect.Message {
	mi := &file_parsed_vision_parsed_vision_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Robot.ProtoReflect.Descriptor instead.
func (*Robot) Descriptor() ([]byte, []int) {
	return file_parsed_vision_parsed_vision_proto_rawDescGZIP(), []int{0}
}

func (x *Robot) GetRobotId() uint32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *Robot) GetPos() *ssl_vision.Vector2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Robot) GetOrientation() float32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

func (x *Robot) GetVel() *ssl_vision.Vector2 {
	if x != nil {
		return x.Vel
	}
	return nil
}

type ParsedFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robots []*Robot            `protobuf:"bytes,1,rep,name=robots,proto3" json:"robots,omitempty"`
	Ball   *ssl_vision.Vector2 `protobuf:"bytes,2,opt,name=ball,proto3" json:"ball,omitempty"`
}

func (x *ParsedFrame) Reset() {
	*x = ParsedFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parsed_vision_parsed_vision_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParsedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedFrame) ProtoMessage() {}

func (x *ParsedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_parsed_vision_parsed_vision_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedFrame.ProtoReflect.Descriptor instead.
func (*ParsedFrame) Descriptor() ([]byte, []int) {
	return file_parsed_vision_parsed_vision_proto_rawDescGZIP(), []int{1}
}

func (x *ParsedFrame) GetRobots() []*Robot {
	if x != nil {
		return x.Robots
	}
	return nil
}

func (x *ParsedFrame) GetBall() *ssl_vision.Vector2 {
	if x != nil {
		return x.Ball
	}
	return nil
}

var File_parsed_vision_parsed_vision_proto protoreflect.FileDescriptor

var file_parsed_vision_parsed_vision_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x61, 0x72, 0x73, 0x65, 0x64, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2f,
	0x70, 0x61, 0x72, 0x73, 0x65, 0x64, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x73, 0x73, 0x6c, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2f,
	0x73, 0x73, 0x6c, 0x5f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x05, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6f,
	0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x03, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x32, 0x52, 0x03, 0x76, 0x65, 0x6c, 0x22, 0x4b, 0x0a, 0x0b, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74,
	0x52, 0x06, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x04, 0x62, 0x61, 0x6c, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32,
	0x52, 0x04, 0x62, 0x61, 0x6c, 0x6c, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x69, 0x55, 0x2d, 0x53, 0x65, 0x65, 0x47, 0x6f, 0x61, 0x6c,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65,
	0x64, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parsed_vision_parsed_vision_proto_rawDescOnce sync.Once
	file_parsed_vision_parsed_vision_proto_rawDescData = file_parsed_vision_parsed_vision_proto_rawDesc
)

func file_parsed_vision_parsed_vision_proto_rawDescGZIP() []byte {
	file_parsed_vision_parsed_vision_proto_rawDescOnce.Do(func() {
		file_parsed_vision_parsed_vision_proto_rawDescData = protoimpl.X.CompressGZIP(file_parsed_vision_parsed_vision_proto_rawDescData)
	})
	return file_parsed_vision_parsed_vision_proto_rawDescData
}

var file_parsed_vision_parsed_vision_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_parsed_vision_parsed_vision_proto_goTypes = []interface{}{
	(*Robot)(nil),              // 0: Robot
	(*ParsedFrame)(nil),        // 1: ParsedFrame
	(*ssl_vision.Vector2)(nil), // 2: Vector2
}
var file_parsed_vision_parsed_vision_proto_depIdxs = []int32{
	2, // 0: Robot.pos:type_name -> Vector2
	2, // 1: Robot.vel:type_name -> Vector2
	0, // 2: ParsedFrame.robots:type_name -> Robot
	2, // 3: ParsedFrame.ball:type_name -> Vector2
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_parsed_vision_parsed_vision_proto_init() }
func file_parsed_vision_parsed_vision_proto_init() {
	if File_parsed_vision_parsed_vision_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parsed_vision_parsed_vision_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Robot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parsed_vision_parsed_vision_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParsedFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parsed_vision_parsed_vision_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parsed_vision_parsed_vision_proto_goTypes,
		DependencyIndexes: file_parsed_vision_parsed_vision_proto_depIdxs,
		MessageInfos:      file_parsed_vision_parsed_vision_proto_msgTypes,
	}.Build()
	File_parsed_vision_parsed_vision_proto = out.File
	file_parsed_vision_parsed_vision_proto_rawDesc = nil
	file_parsed_vision_parsed_vision_proto_goTypes = nil
	file_parsed_vision_parsed_vision_proto_depIdxs = nil
}
